version: '3'
services:
  nginx:
    build:
      context: ../nginx
      args:
        - NGINX_VER=1.17.9-alpine
    container_name: magento_nginx
    privileged: true
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./www:/var/www
      - ./nginx/log:/var/log/nginx
    restart: always
    depends_on:
      - php
    networks:
      magento:
        aliases:
          - net-magento-nginx
  php:
    build: 
      context: ../php
      args:
        - PHP_VER=8.1.23-fpm-alpine
        - PHP_REDIS_VER=5.2.2
        - SWOOLE_VER=4.5.1
        - COMPOSER_URL=https://mirrors.aliyun.com/composer/
    container_name: magento_php
    privileged: true
    restart: always
    expose:
      - "9000"
      - "9003"
    volumes:
      - ./www:/var/www
      - ./php/74-fpm/php/php.ini:/usr/local/etc/php/php.ini
      - ./php/74-fpm/logs:/var/log/php
    networks:
      magento:
        aliases:
          - net-magento-php

  mysql:
    build:
      context: ../mysql
      args:
        - MYSQL_VER=8.0.36
    container_name: magento_mysql
    privileged: true
    restart: always
    ports:
      - "23306:3306"
    volumes:
      - ./mysql/log:/var/log/mysql
      - ./mysql/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=Root@123
    networks:
      magento:
        aliases:
          - net-magento-mysql      

  redis:
    build:
      context: ../redis/6.x
    container_name: redis_6_2_3
    privileged: true
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data
      - ./redis/logs:/var/log
    networks:
      magento:
        aliases:
          - net-redis-6-2-3

  elasticsearch:
    build:
      context: ../elasticsearch/7_17
    container_name: elasticsearch_7_17
    privileged: true
    environment:
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./elasticsearch/data717:/usr/share/elasticsearch/data
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    networks:
      magento:
        aliases:
          - net-elasticsearch-7-17

  rabbitmq:
    build:
      context: ../rabbitmq
    container_name: rabbitmq
    restart: always
    hostname: rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      - RABBITMQ_ERLANG_COOKIE=peace
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=root  
    networks:
      magento:
        aliases:
          - net-rabbitmq-3-8-16                   

networks:
  magento:
    driver: bridge
